# =========================
# ESTÁGIO: Desenvolvimento
# =========================
FROM node:22-slim

WORKDIR /app

# Instala git apenas se necessário para resolver dependências de pacotes
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Copia as definições de pacotes primeiro para aproveitar o cache do Docker
COPY package*.json ./

# Instala todas as dependências (incluindo devDependencies)
RUN npm install

# Copia o restante do código-fonte do frontend para o container
COPY . .

# Comando final de build
# RUN npm run build

EXPOSE 5173
CMD ["npm", "run", "dev"]